DELIMITER %
CREATE PROCEDURE TRANSACTION (FROM_ACCOUNT INT, TO_ACCOUNT INT, AMOUNT DECIMAL(15,2))
BEGIN
DECLARE FROM_BALANCE DECIMAL(15,2);
SELECT BALANCE INTO FROM_BALANCE FROM ACCOUNT WHERE account_id=FROM_ACCOUNT;
IF (FROM_BALANCE >= AMOUNT) THEN 
	UPDATE ACCOUNT SET BALANCE = BALANCE - AMOUNT WHERE account_id=FROM_ACCOUNT;	
	UPDATE ACCOUNT SET BALANCE = BALANCE + AMOUNT WHERE account_id=TO_ACCOUNT;
	INSERT INTO TRANSACTION (account_id,transaction_type,amount) VALUES (FROM_ACCOUNT,'OUT',AMOUNT);
	INSERT INTO TRANSACTION (account_id,transaction_type,amount) VALUES (TO_ACCOUNT,'IN',AMOUNT);
ELSE
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT='INSUFFICIENT BALANCE IN FROM ACCOUNT';
END IF;
END%