DELIMITER %
CREATE PROCEDURE DEPOSIT(IN FROM_ACCOUNT INT, IN AMOUNT DECIMAL(15,2))
BEGIN
    DECLARE FROM_ACC_BALANCE DECIMAL(15,2);
    IF (SELECT COUNT(*) FROM ACCOUNT WHERE ACCOUNT_ID = FROM_ACCOUNT) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ACCOUNT DOES NOT EXIST';
    ELSE
        SELECT BALANCE INTO FROM_ACC_BALANCE FROM ACCOUNT WHERE ACCOUNT_ID = FROM_ACCOUNT;
        UPDATE ACCOUNT SET BALANCE = BALANCE + AMOUNT WHERE ACCOUNT_ID = FROM_ACCOUNT;
		INSERT INTO TRANSACTION(ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT)VALUES (FROM_ACCOUNT, 'DEPOSIT', AMOUNT);
    END IF;
END %